### ISSUE TITLE
func decompose() returns nil for associated values of zero size

### ISSUE THREAD

**Issue by MutatingFunc** [gringoireDM/EnumKit#4]
Hi, I've come across a bit of an edge-case:
```
struct ExampleView: View {
    var body: some View {
        EmptyView()
    }
}
enum MyClosedSetOfViews {
    case example(ExampleView)
}

let value = MyClosedSetOfViews.example(ExampleView())
value[case: MyClosedSetOfViews.example] // == nil
```

I've briefly experimented in a fork, adding in a few tests (which fail as expected), but as far as I can tell this is a limitation in the Mirror API which can only be worked around by padding the case with an additional associated value of non-zero size.

The root cause of the problem is that the return children array of Mirror is empty, so this looks like a Swift language bug, but I'd like to open this issue in case anyone can find a viable fix that I've overlooked.

**Comment by MutatingFunc** [comment]
I've created a Swift bug to track this: [SR-12255](https://bugs.swift.org/browse/SR-12255)

**Comment by MutatingFunc** [comment]
Apparently this was fixed in swift-master a few days ago. Once released, this example should just start working, no changes needed!

**Comment by gringoireDM** [comment]
Let me see if I can fix it for the time being. that's a really good use case I should have tests for anyway. Thank you!

**Comment by gringoireDM** [comment]
Hi, I just tried to reproduce the issue, and I can't. All my tests are passing. Can you prepare a branch with failing tests? I'm on Xcode 11.3.1

**Comment by MutatingFunc** [comment]
Could you check out my [Fork](https://github.com/MutatingFunc/EnumKit)? The tests I've added there are failing for me.

I should be able to prepare a branch later in the day if that would be preferable.

**Comment by gringoireDM** [comment]
No worries, the fork is enough

**Comment by gringoireDM** [comment]
Reproduced and fixed. will deploy an 1.1.1 by the end of the day. Thank you very much for your support.

**Comment by MutatingFunc** [comment]
Awesome! Thanks.

**Comment by gringoireDM** [comment]
I've opened a PR. If you have some time I would appreciate you to have a look
https://github.com/gringoireDM/EnumKit/pull/5
